### ISSUE TITLE
DPAFLoader cannot read its own files

### ISSUE THREAD

**Issue by PaddiM** [nvpro-pipeline/pipeline#1]
Hi,

found a bug in DPAFLoader:

bool  DPAFLoader::testDPVersion( void )
{
  m_line = 0;
  getNextLine();
  return( m_currentLine == "#DPSG V1.0");
}

but the header of a DAPF file starts with:

#DPAF V1.0

Greets,

Patrik

**Comment by nvpro-pipeline** [comment]
Hi Patrik,

thanks for the report. It's fixed in master now. Please keep in mind that the DPAF file format is used as debug format by us. We're not keeping if downwards compatible if we have to change the format for any reason.

Best Regards,

Markus
