### ISSUE TITLE
Missing comma in HOOPSLoader file extension list

### ISSUE THREAD

**Issue by joulsoun** [nvpro-pipeline/pipeline#10]
Hi,
There's a comma missing in the file extension list of HOOPSLoader.cpp, ln: 101
https://github.com/nvpro-pipeline/pipeline/blob/master/dp/sg/io/HOOPS/Loader/HOOPSLoader.cpp#L101

This breaks both VDA and VRML file extensions.

**Comment by mtavenrath** [comment]
Thanks for reporting. The issue is fixed now.
