### ISSUE TITLE
std::array defaults

### ISSUE THREAD

**Issue by CBenghi** [nvpro-pipeline/pipeline#13]
Hello,

I've tried to compile on Windows, but I'm having a couple of problems, the first one is, I think, trivial.

'dp/sg/core/LightSource.h' and 'dp/sg/core/PipelineData.h' have invalid syntax (according to msvc). There are four entries of the following line:

```
const std::array<float, 3> & attenuations = { 1.0f, 0.0f, 0.0f }
```
that need to become

```
const std::array<float, 3> & attenuations = { { 1.0f, 0.0f, 0.0f } }
```

AFAIK this applies to gcc as well according to [this stackoverflow answer](https://stackoverflow.com/questions/19152192/how-to-use-a-default-argument-for-stdarray-array-must-be-initialized-with-a).

Have i done something wrong in CMake that would otherwise make this syntax ok?

**Comment by asuessenbach** [comment]
Hi CBenghi,

what kind of error do you get, using which msvc version?

According to the [C++ reference](http://www.cplusplus.com/reference/array/array/array/), the initializer_list of a std::array needs just single braces.
