### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/pipeline#5]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [Object assignment operator](https://github.com/nvpro-pipeline/pipeline/blob/7995c6b8b54a0b0a38fbdc81e8f83ce0655ef144/dp/sg/core/src/Object.cpp#L155 "Object::operator= function")
* [SFImage destructor](https://github.com/nvpro-pipeline/pipeline/blob/8a2e1c9d79ba4b3b6f9328355d017ed7a303a9cd/dp/sg/io/WRL/Loader/VRMLTypes.cpp#L821 "Destructor for SFImage")

**Comment by mtavenrath** [comment]
The null pointer checks are relics of old code pieces where a compiler had problems with delete 0. We're constantly removing them if there's some time left.
