### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [nvpro-pipeline/pipeline#6]
Would you like to [wrap any pointer data members](https://github.com/nvpro-pipeline/pipeline/blob/8a2e1c9d79ba4b3b6f9328355d017ed7a303a9cd/apps/Viewer/src/QSingleItemSquareLayout.cpp#L7 "Update candidate: QSingleItemSquareLayout class") with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

**Comment by mtavenrath** [comment]
Yes, new code of this pipeline is using smart pointers for all code. There's still legacy code which hasn't been updated to used smartpointers. If we encounter those code pieces and have some time left we're fixing those places.
