### ISSUE TITLE
About deleted GTC nvpro sessions..

### ISSUE THREAD

**Issue by oscarbg** [nvpro-pipeline/pipeline#7]
Hi,
just a month ago or two when initial GTC sessions were published I saved on notepad some ones I was interested.. now seeing actual sessions sessions seems two sessions got deleted:
S6132 - Nvpro-Pipeline: Using LLVM to Accelerate Your OpenGL Rendering Core
S6133 - Nvpro-Pipeline: Vulkan as New Graphics Backend
so question is if altough sessions have been deleted the features are talking about are or are going to be avaiable soon on github.. i.e.:
1) does nvpro-pipeline support Vulkan as backend actually or soon?
2) what about "Using LLVM to Accelerate Your OpenGL Rendering Core"? I remember reading about something being JITted via LLVM.. is that already commited?
thanks..

**Comment by mtavenrath** [comment]
1) We started a Vulkan backend, but it has been deferred to complete vkcpp which has a bigger audience. Work will continue after GTC.
2) The parameter update loop and the per GI renderloop will be JITTed. Nothing has been commited yet.

**Comment by mtavenrath** [comment]
Not an issue. Closing.
